### PR TITLE
Adding footprint for LV25-P

### PR DESCRIPTION
**Pull request by cedricboudinet**
Hello
I created the schematics, footprint and 3dshape model for LEM LV 25-P and LA 25-P

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi and thanks for your contribution.

We have a set of rules that footprints and symbols must follow to be acepted for this lib (KLC).  You can find them here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention We are currently vamping them up with examples and better explanations and are incorporating rules that have been developed in the past months while reviewing footprints7symbols for this lib. You can find the reworked version here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC (Please follow the rules therein!) Also see the discussion on that new version: https://github.com/KiCad/kicad-library/issues/879

There is also a set of scripts that helps you check these rules (make sure to use the option `-v` !) and even fix some issues automatically (option `--fix`): https://github.com/KiCad/kicad-library-utils

Please ensure to follow these rules with your footprint, i.e. add outline on F.Fab, add courtyard, move anchor to pin1 ...

Best,
JAN

**Comment by cedricboudinet** [comment]
Hi and thanks for the hints
I'll (try to) correct the footprints.
About the footprint naming, should it be LEM_LA25-P since it is vendor specific or should it be more in accordance with the other footprints in the library?
The LV is a voltage sensor (but still based on a current transducer). Is this it ok to remain in this library?
Regards
Cedric

**Comment by jkriege2** [comment]
I would leave the names as they are ... Maybe add `HallEffectTransducer_` in front ... that's how we do it in other libs, but we would have to change it here at some point1

JAN

**Comment by cedricboudinet** [comment]
Dear Jan
Is it ok with the last modification? 
Bests

**Comment by jkriege2** [comment]
Hi!

I ran our check scripts on your footprints. This is the result:

```
Checking footprint 'LEM_LA25-P':
  Violating Rule 7.3
    Silkscreen requirements
    Reference label errors:
     - Reference value is 'LA25P_1', expected: 'REF**'
  Violating Rule 7.4
    Fabrication layer requirements
    Second Reference Designator missing
     - Add RefDes to F.Fab layer with '%R'
  Violating Rule 7.5
    CrtYd layer contains component courtyard, 0.05mm line width on 0.01mm grid
    Courtyard clearance error
     - A courtyard clearance in the range 0.0...0.5mm was found, but 0.25mm was expected.
The recommended courtyard rectangle would be:
    {'x': -5.33, 'y': -7.87, 'width': 38.6, 'height': 15.74}mm.

Checking footprint 'LEM_LV25-P':
  Violating Rule 7.3
    Silkscreen requirements
    Reference label errors:
     - Reference value is 'LV 25-P_1', expected: 'REF**'
  Violating Rule 7.4
    Fabrication layer requirements
    Second Reference Designator missing
     - Add RefDes to F.Fab layer with '%R'
  Violating Rule 7.5
    CrtYd layer contains component courtyard, 0.05mm line width on 0.01mm grid
    Courtyard clearance error
     - A courtyard clearance in the range 0.0...0.51mm was found, but 0.25mm was expected.
The recommended courtyard rectangle would be:
    {'y': -4.07, 'x': -21.84, 'height': 29.71, 'width': 28.44}mm.
```

Please fix violations of rules 7.3 and 7.4 as suggested. Then move the yourtyard, so it's outside the outline (which is on F.Fab) and therefore visible after assembly. Finally add a courtyard which has an offset of 0.25mm to the outside around the outline on F.Fab. Here's an example for a relais:
2017-03-07 21_19_50-footprint editor no active library

Best,
JAN

PS: The new KLCs (preview available here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC) now also have images illustrating the rules!

**Comment by cedricboudinet** [comment]
Hi
When I run: ./check_kicad_mod.py ../../modules/Hall-Effect_Transducers_LEM.pretty/LEM_LA25-P.kicad_mod -v

I have a different log message :
```
checking module: LEM_LA25-P
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.
      
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      A courtyard clearance in the range -0.0...0.5mm was found, but 0.25mm was expected.
      The recommendet courtyard rectangle would be:
          {'y': -7.87, 'x': -5.33, 'height': 15.74, 'width': 38.6}mm.
```
I use the latest version of check_kicad_mod.py from kicad-library-utils/pcb. Do you use another tool to have the check result you put in your last comment?

Bests
Cedric

**Comment by jkriege2** [comment]
Yes I used a version from this PR: https://github.com/KiCad/kicad-library-utils/pull/81

**Comment by SchrodingersGat** [comment]
Sorry Travis wasn't enabled for this repo - now it is :)

**Comment by cedricboudinet** [comment]
Dear Jan
I updated the footprints. Is it fine?
Cedric

**Comment by jkriege2** [comment]
yes, thanks!

JAN

**Pull request merged**
